### ISSUE TITLE
unmet peer esbuild@^0.14.0: found 0.15.0

### ISSUE THREAD

**Issue by Valexr** [TurtIeSocks/esbuild-plugin-eslinter#3]
New minor version esbuild avialable now [0.15.0](https://github.com/evanw/esbuild/releases/tag/v0.15.0)

**Comment by TurtIeSocks** [comment]
Resolved in #4. Thanks for the heads up!

**Comment by Valexr** [comment]
Very useful plugin 👍🏻

**Comment by TurtIeSocks** [comment]
Glad to hear it :)
